// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqyZ8whUdkuEqbntKGlj2dWMAfBIkIRGI',
    appId: '1:348957091052:web:86fa2b49264dec8f8cb1c9',
    messagingSenderId: '348957091052',
    projectId: 'chat-app-aa4eb',
    authDomain: 'chat-app-aa4eb.firebaseapp.com',
    storageBucket: 'chat-app-aa4eb.appspot.com',
    measurementId: 'G-0ZPKTB73H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF5_I4pXL3hFvtSx_OsxeuzgV0_a8p74w',
    appId: '1:348957091052:android:7eb7340dde03a86a8cb1c9',
    messagingSenderId: '348957091052',
    projectId: 'chat-app-aa4eb',
    storageBucket: 'chat-app-aa4eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1-HmUpFJYSO4Gx63v1e-EE7TqIifZ3EU',
    appId: '1:348957091052:ios:988eee6b80cd895a8cb1c9',
    messagingSenderId: '348957091052',
    projectId: 'chat-app-aa4eb',
    storageBucket: 'chat-app-aa4eb.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
